import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import { Card, CardContent, Grid, Stack, Typography } from '@mui/material'
import PageHeader from '../components/PageHeader.jsx'
import {
  deliveriesPerDay,
  deliveryTimeDistribution,
  utilizationRate,
} from '../data/mockData.js'

const utilizationColors = ['#0ea5e9', '#14b8a6', '#f97316']

function AnalyticsPage() {
  return (
    <Stack spacing={2}>
      <PageHeader
        title="Analytics"
        subtitle="Explore logistics performance data generated by the HiveDeliver simulation."
      />

      <Grid container spacing={1.2}>
        <Grid size={{ xs: 12, lg: 6 }}>
          <Card className="hover-lift" sx={{ height: '100%' }}>
            <CardContent>
              <Typography variant="h6" sx={{ mb: 1.2 }}>
                Deliveries per day
              </Typography>
              <ResponsiveContainer width="100%" height={270}>
                <BarChart data={deliveriesPerDay}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="day" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="deliveries" fill="#0f766e" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </Grid>

        <Grid size={{ xs: 12, lg: 6 }}>
          <Card className="hover-lift" sx={{ height: '100%' }}>
            <CardContent>
              <Typography variant="h6" sx={{ mb: 1.2 }}>
                Drone utilization rate
              </Typography>
              <ResponsiveContainer width="100%" height={270}>
                <PieChart>
                  <Pie data={utilizationRate} dataKey="value" nameKey="name" outerRadius={92} label>
                    {utilizationRate.map((entry, index) => (
                      <Cell key={entry.name} fill={utilizationColors[index % utilizationColors.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </Grid>

        <Grid size={{ xs: 12 }}>
          <Card className="hover-lift">
            <CardContent>
              <Typography variant="h6" sx={{ mb: 1.2 }}>
                Delivery time distribution
              </Typography>
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={deliveryTimeDistribution}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="window" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line
                    type="monotone"
                    dataKey="minutes"
                    stroke="#f97316"
                    strokeWidth={3}
                    dot={{ r: 4 }}
                    activeDot={{ r: 6 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Stack>
  )
}

export default AnalyticsPage
